{% set name = "tmm" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tmm-{{ version }}.tar.gz
  sha256: 2982683aab12b5bb1ee9910a44d7c6421885ab581d22bebb615351dd70cb8ced

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python 3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - numpy >=1.7

test:
  imports:
    - tmm
  commands:
    - pip check
  requires:
    - python 3.6
    - pip

about:
  home: http://pypi.python.org/pypi/tmm
  summary: Simulate light propagation in multilayer thin and/or thick films using the fresnel equations and transfer matrix method.
  doc_url: https://pythonhosted.org/tmm/
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - benvial
